services:
  - type: web
    name: django-web
    env: python
    buildCommand: ""
    startCommand: gunicorn your_project_name.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: your_project_name.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
