# Generated by Django 5.2.1 on 2025-06-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SellerRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("add", models.CharField(max_length=50)),
                ("mob", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=8)),
            ],
            options={
                "verbose_name_plural": "Seller Registraction",
            },
        ),
    ]
