# Generated by Django 5.2.1 on 2025-06-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellerregistration",
            name="add",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="sellerregistration",
            name="email",
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name="sellerregistration",
            name="mob",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="sellerregistration",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
