# Generated by Django 5.2.1 on 2025-06-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0002_alter_sellerregistration_add_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sellerregistration",
            options={"verbose_name_plural": "Seller Registration"},
        ),
    ]
