# Generated by Django 5.2.1 on 2025-06-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0003_alter_sellerregistration_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerregistration",
            name="accept",
            field=models.BooleanField(default=False),
        ),
    ]
