# Generated by Django 5.2.1 on 2025-06-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0004_sellerregistration_accept"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellerregistration",
            name="email",
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name="sellerregistration",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
