# Generated by Django 5.2.1 on 2025-05-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("mob", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=8)),
                ("add", models.TextField()),
            ],
        ),
    ]
