# Generated by Django 5.2.1 on 2025-05-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_registration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="add",
            field=models.CharField(max_length=50),
        ),
    ]
