# Generated by Django 5.2.1 on 2025-05-22 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.PositiveBigIntegerField()),
                ("date_time", models.DateTimeField(auto_now=True)),
                ("payment_mode", models.CharField(max_length=50)),
                ("transaction_id", models.CharField(max_length=100)),
                ("total_amount", models.PositiveIntegerField(default=0)),
                ("add", models.TextField()),
                ("mob", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("pin_code", models.CharField(max_length=6)),
                (
                    "pro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.product"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.registration",
                    ),
                ),
            ],
        ),
    ]
