# Generated by Django 5.2.1 on 2025-05-24 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0006_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.product"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.registration",
                    ),
                ),
            ],
        ),
    ]
