# Generated by Django 5.2.1 on 2025-05-25 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_wishlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.PositiveBigIntegerField()),
                ("total_amount", models.PositiveIntegerField(default=0)),
                ("order_id", models.PositiveBigIntegerField(max_length=50)),
                (
                    "pro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.product"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.registration",
                    ),
                ),
            ],
        ),
    ]
