# Generated by Django 5.2.1 on 2025-05-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0008_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="order_id",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
