# Generated by Django 5.2.1 on 2025-05-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0011_alter_cart_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="total_amount",
            field=models.PositiveIntegerField(),
        ),
    ]
