# Generated by Django 5.2.1 on 2025-05-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0012_alter_cart_total_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="total_amount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
