# Generated by Django 5.2.1 on 2025-05-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0013_alter_cart_total_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="order_id",
            field=models.PositiveBigIntegerField(),
        ),
    ]
