# Generated by Django 5.2.1 on 2025-05-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0014_alter_cart_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="order_id",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
