# Generated by Django 5.2.1 on 2025-05-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0015_alter_cart_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="ordered",
            field=models.BooleanField(default=False),
        ),
    ]
