# Generated by Django 5.2.1 on 2025-05-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0016_cart_ordered"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="ordered",
            field=models.BooleanField(default=False),
        ),
    ]
