# Generated by Django 5.2.1 on 2025-05-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0017_order_ordered"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="prods",
            field=models.ManyToManyField(to="app1.cart"),
        ),
    ]
