# Generated by Django 5.2.1 on 2025-06-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0018_order_prods"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="pro",
        ),
        migrations.RemoveField(
            model_name="order",
            name="qty",
        ),
        migrations.AlterField(
            model_name="order",
            name="prods",
            field=models.ManyToManyField(blank=True, null=True, to="app1.cart"),
        ),
        migrations.AlterField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
