# Generated by Django 5.2.1 on 2025-06-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0019_remove_order_pro_remove_order_qty_alter_order_prods_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="prods",
            field=models.ManyToManyField(to="app1.cart"),
        ),
    ]
