# Generated by Django 5.2.1 on 2025-06-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0020_alter_order_prods"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="total_amount",
            field=models.PositiveIntegerField(),
        ),
    ]
