# Generated by Django 5.2.1 on 2025-06-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0021_alter_cart_total_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.PositiveIntegerField(),
        ),
    ]
