# Generated by Django 5.2.1 on 2025-06-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0023_product_added_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Order Placed", "Order Placed"),
                    ("On thbe way", "On thbe way"),
                    ("Delivered", "Delivered"),
                ],
                default="Pending",
                verbose_name="Order Status",
            ),
        ),
    ]
