# Generated by Django 5.2.1 on 2025-06-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0024_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.AddField(
            model_name="cart",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Order Placed", "Order Placed"),
                    ("On thbe way", "On thbe way"),
                    ("Delivered", "Delivered"),
                ],
                default="Pending",
                verbose_name="Order Status",
            ),
        ),
    ]
