# Generated by Django 5.2.1 on 2025-06-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0025_remove_order_status_cart_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Order Placed", "Order Placed"),
                    ("On the way", "On the way"),
                    ("Delivered", "Delivered"),
                ],
                default="Pending",
                verbose_name="Order Status",
            ),
        ),
    ]
